### ISSUE TITLE
doHover isn't complete when I write the namespace

### ISSUE THREAD

**Issue by GiulioCocconi** [clangd/coc-clangd#425] opened 2022-03-21 20:59 UTC
### Please describe the problem.
When I run `CocAction('doHover')` the documentation is better when I don't explicitly write the namespace (for example when I use `using namespace std;`)
![Screenshot at 2022-03-21 21-50-41](https://user-images.githubusercontent.com/31406038/159362591-754ea317-6c77-4f86-9581-850714e57c8d.png)
![Screenshot at 2022-03-21 21-51-47](https://user-images.githubusercontent.com/31406038/159362609-6750b4a7-afc5-4463-a11d-e198ab31cd36.png)

**Comment by sam-mccall** [comment] 2022-03-21 21:55
Agree. This is a dupe of https://github.com/clangd/clangd/issues/989

The issue is that std::atexit is an alias of ::atexit, and we're showing hover for the alias instead of the underlying symbol. We should show the underlying symbol in this case (though there are cases where the alias is more useful!)

I think you'll find that `using namespace std` is not actually doing anything in that example, but in any case using directives are different than using declarations and do not introduce aliases.

**Closed by sam-mccall** 2022-03-21 21:55 UTC
Labels: bug
