### ISSUE TITLE
.h header being treated as C++ instead C

### ISSUE THREAD

**Issue by NickWilde263** [clangd/coc-clangd#443] opened 2022-04-24 05:12 UTC
Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

```c
// clangd complains about invalid
// use of `this` from C++ keyword while
// in C `this` is legal identifier

void downloader_free(struct downloader* this);
```

**Logs**
I[11:59:34.621] Debian clangd version 11.0.1-2
I[11:59:34.621] PID: 26309                                                                                                                                                     I[11:59:34.621] Working directory: /home/fox/FluffyVM                                                                                                                          I[11:59:34.621] argv[0]: /usr/bin/clangd                                                                                                                                       I[11:59:34.621] Starting LSP over stdin/stdout                                                                                                                                 I[11:59:34.623] <-- initialize(0)                                                                                                                                              I[11:59:34.627] --> reply:initialize(0) 3 ms
I[11:59:34.702] <-- initialized
I[11:59:34.702] <-- textDocument/didOpen
I[11:59:34.705] Failed to find compilation database for /home/fox/FluffyVM/test_header.h
I[11:59:34.705] ASTWorker building file /home/fox/FluffyVM/test_header.h version 1 with command clangd fallback
[/home/fox/FluffyVM]
/usr/lib/llvm-11/bin/clang -xobjective-c++-header /home/fox/FluffyVM/test_header.h -xc -fblocks -D_POSIX_C_SOURCE=200809L -fsyntax-only -resource-dir=/usr/lib/llvm-11/lib/clang/11.0.1
I[11:59:34.725] --> textDocument/clangd.fileStatus
I[11:59:34.883] --> textDocument/publishDiagnostics
I[11:59:34.884] --> textDocument/clangd.fileStatus
I[12:04:10.763] <-- textDocument/didClose
I[12:04:10.764] --> textDocument/publishDiagnostics

**System information**
Clangd version (from the log, or `clangd --version`): Debian clangd version 11.0.1-2
clangd extension version (from `:CocInfo`): 0.0.80-c9f7aa24 2022-03-24 23:11:36 +0800

Operating system:
Debian 11

**Comment by NickWilde263** [comment] 2022-04-24 05:14
```json
{                                                                                                   
  "clangd.fallbackFlags": ["-xc", "-fblocks", "-D_POSIX_C_SOURCE=200809L"]                         }
``` My coc config

**Comment by fannheyward** [comment] 2022-05-22 11:17
Can't reproduce with clangd 14, upgrade your clangd and try again. Close it because it's not coc-clangd's issue.

**Closed by fannheyward** 2022-05-22 11:17 UTC
Labels: bug

**Comment by NickWilde263** [comment] 2022-05-24 07:52
> Can't reproduce with clangd 14, upgrade your clangd and try again. Close it because it's not coc-clangd's issue.

ok
