### ISSUE TITLE
cpp auto complete erro

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [clangd/coc-clangd#330] opened 2021-08-16 11:54 UTC
```
#include <header>de 
printf(const char *__restrict __format, ...)tf
```
when i use coc-clangd， in the end has word "de" "tf"
clangd version 12.0

**Comment by wangwenqiangGitHub** [comment] 2021-08-16 12:59
Enter to choose completion item

**Comment by fannheyward** [comment] 2021-08-16 13:04
Should be fixed on latest coc https://github.com/neoclide/coc.nvim/issues/3290

**Closed** 2021-08-17 01:43 UTC
Labels: bug

**Comment by Andoku** [comment] 2021-08-30 20:48
@fannheyward I am still experiencing this bug.
CocInfo:
```
vim version: VIM - Vi IMproved 8.2 8022681
node version: v16.8.0
coc.nvim version: 0.0.80-3086844413
coc.nvim directory: /Users/antontatuev/.vim/plugged/coc.nvim
term: iTerm.app
platform: darwin
```

**Comment by fannheyward** [comment] 2021-09-01 02:23
@Andoku tested with vim 8.2.3350 with latest coc.nvim, can't reproduce this.

**Comment by Andoku** [comment] 2021-09-05 11:31
@fannheyward But I am still getting this. How can I help to debug this?

**Comment by fannheyward** [comment] 2021-09-05 12:38
@Andoku please test with minimal vimrc, and provided steps to reproduce this issue.
