### ISSUE TITLE
coc-clangd: `:wq` hangs when editing git commits

### ISSUE THREAD

**Issue by tony** [clangd/coc-clangd#517] opened 2022-10-31 17:05 UTC
Since https://github.com/clangd/coc-clangd/commit/d23b566780f176162adb88776cd7962444acee14, coc.nvim + coc-clangd has caused `:wq` to hang in `git commit` w/ vim.

Only this coc plugin gives the issue.

**Logs**
@fannheyward I want to provide a solid bug report, but not sure how! I need help for that:

1. Is their a minimal VIM config for coc.nvim + coc-clangd you can provide for user's giving bug reports/recreations?
2. Is there a list of instructions for how to give a debug report for coc plugisn in general?
3. How do I provide logs for `:wq` in particular?  

**System information**
Clangd version (from the log, or `clangd --version`): 

```
Ubuntu clangd version 14.0.0-1ubuntu1
Features: linux+grpc
Platform: x86_64-pc-linux-gnu
```

clangd extension version (from `:CocInfo`): Doesn't show
Operating system: WSL 2

```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

**Comment by tony** [comment] 2022-11-01 01:27
## versions

vim version: VIM - Vi IMproved 9.0 9000822
node version: v19.0.0
coc.nvim version: 0.0.82-120330f 2022-11-01 02:20:28 +0800
coc.nvim directory: /home/tony/.vim/plugged/coc.nvim
term: tmux
platform: linux

## Log of coc.nvim

2022-10-31T20:26:22.022 INFO (pid:10926) [coc-git] - Looking for git in: git
2022-10-31T20:26:22.026 INFO (pid:10926) [plugin] - coc.nvim initialized with node: v19.0.0 after 117ms
2022-10-31T20:26:22.944 INFO (pid:10926) [attach] - receive notification: showInfo []

**Comment by fannheyward** [comment] 2022-11-01 01:31
I can't reproduce `:wq` hangs in git-commit files. Still working on this.

**Comment by tony** [comment] 2022-11-01 01:34
>  I can't reproduce :wq hangs in git-commit files. Still working on this.

If you cannot recreate, I will follow any instructions you wish to create a minimal recreation.  (Though depending on how time consuming, it may need to be during the weekend)

**Comment by fannheyward** [comment] 2022-11-01 01:43
I'm node 18, have no idea whether this related or not.

https://github.com/neoclide/coc.nvim/issues/3824, someone reported similar issue, but this should be fixed in coc.nvim side already.

**Comment by tony** [comment] 2022-11-01 03:03
@fannheyward I recall the fix at https://github.com/neoclide/coc.nvim/issues/3824.  The coc.nvim update sped it up a bit.

coc-clangd still makes `:wq` hang for me hangs noticeably - no more than a few seconds (verse instantly exiting without it)

I will follow up with more debug info

**Comment by fannheyward** [comment] 2022-11-16 07:29
I've made a temporary fix for this, upgrade your coc-clangd by CocUpdate and try again.

**Closed by fannheyward** 2022-11-16 07:29 UTC
Labels: bug
